CREATE OR REPLACE VIEW staging.vw_players
            (
             id,
             player_key,
             name,
             position,
             week,
             started,
             team_key,
             person,
             manager_name,
             league_id,
             league_name,
             league_season,
             points,
             passing_yards,
             passing_touchdowns,
             passing_interceptions,
             rushing_attempts,
             rushing_yards,
             rushing_touchdowns,
             receptions,
             receiving_yards,
             receiving_touchdowns,
             return_touchdowns,
             two_point_conversions,
             fumbles_lost,
             targets,
             offensive_fumble_return_td,
             field_goals_0_19_yards,
             field_goals_20_29_yards,
             field_goals_30_39_yards,
             field_goals_40_49_yards,
             field_goals_50_plus_yards,
             point_after_attempt_made,
             points_allowed,
             sack,
             interception,
             fumble_recovery,
             touchdown,
             safety,
             block_kick,
             kickoff_and_punt_return_touchdowns,
             points_allowed_0_points,
             points_allowed_1_6_points,
             points_allowed_7_13_points,
             points_allowed_14_20_points,
             points_allowed_21_27_points,
             points_allowed_28_34_points,
             points_allowed_35_plus_points,
             extra_point_returned,
             field_goals_made,
             field_goals_total_yards,
             field_goals_missed)
AS
SELECT players.id,
       player_key,
       players.name,
       position,
       week,
       started,
       players.team_key,
       person_name,
       players.manager_name,
       players.league_id,
       league_name,
       players.league_season,
       points,
       passing_yards,
       passing_touchdowns,
       passing_interceptions,
       rushing_attempts,
       rushing_yards,
       rushing_touchdowns,
       receptions,
       receiving_yards,
       receiving_touchdowns,
       return_touchdowns,
       two_point_conversions,
       fumbles_lost,
       targets,
       offensive_fumble_return_td,
       field_goals_0_19_yards,
       field_goals_20_29_yards,
       field_goals_30_39_yards,
       field_goals_40_49_yards,
       field_goals_50_plus_yards,
       point_after_attempt_made,
       points_allowed,
       sack,
       interception,
       fumble_recovery,
       touchdown,
       safety,
       block_kick,
       kickoff_and_punt_return_touchdowns,
       points_allowed_0_points,
       points_allowed_1_6_points,
       points_allowed_7_13_points,
       points_allowed_14_20_points,
       points_allowed_21_27_points,
       points_allowed_28_34_points,
       points_allowed_35_plus_points,
       extra_point_returned,
       field_goals_made,
       field_goals_total_yards,
       field_goals_missed
FROM staging.players players
         LEFT JOIN public.player_lookup xref ON players.team_key = xref.team_key
         LEFT JOIN public.dim_person prs ON xref.player_id = prs.identity
         JOIN public.dim_league league ON players.league_id = league.identity

ALTER VIEW staging.vw_players
    OWNER TO admin;



CREATE OR REPLACE VIEW staging.vw_matchups
            (id,
             week,
             is_playoffs,
             is_consolation,
             team_1_key,
             team_1_person,
             team_1_nickname,
             team_1_points,
             team_1_projected_points,
             is_bye,
             team_2_key,
             team_2_person,
             team_2_nickname,
             team_2_points,
             team_2_projected_points,
             league_id,
             league_name,
             league_season)
AS
SELECT matchups.id,
       week,
       is_playoffs,
       is_consolation,
       team_1_key,
       prs_one.person_name,
       team_1_nickname,
       team_1_points,
       team_1_projected_points,
       is_bye,
       team_2_key,
       prs_two.person_name,
       team_2_nickname,
       team_2_points,
       team_2_projected_points,
       matchups.league_id,
       league_name,
       matchups.league_season
FROM staging.matchups matchups
         LEFT JOIN public.player_lookup team_one_xref ON matchups.team_1_key = team_one_xref.team_key
         LEFT JOIN public.player_lookup team_two_xref ON matchups.team_2_key = team_two_xref.team_key
         LEFT JOIN public.dim_person prs_one ON team_one_xref.player_id = prs_one.identity
         LEFT JOIN public.dim_person prs_two ON team_two_xref.player_id = prs_two.identity
         JOIN public.dim_league league ON matchups.league_id = league.identity;

ALTER VIEW staging.vw_matchups
    OWNER TO admin;

CREATE OR REPLACE VIEW staging.vw_teams
            (id,
             name,
             team_key,
                person_name,
             number_of_moves,
             number_of_trades,
             clinched_playoffs,
             manager_name,
             division_id,
             draft_grade,
             rank,
             points_for,
             points_against,
             wins,
             losses,
             league_id,
                league_name,
             league_season)
AS
SELECT teams.id,
             teams.name,
             teams.team_key,
             person_name,
             teams.number_of_moves,
             teams.number_of_trades,
             teams.clinched_playoffs,
             teams.manager_name,
             teams.division_id,
             teams.draft_grade,
             teams.rank,
             teams.points_for,
             teams.points_against,
             teams.wins,
             teams.losses,
             teams.league_id,
             league_name,
             teams.league_season
FROM staging.teams teams
         LEFT JOIN public.player_lookup xref ON teams.team_key = xref.team_key
         LEFT JOIN public.dim_person prs_one ON xref.player_id = prs_one.identity
         JOIN public.dim_league league ON teams.league_id = league.identity;

ALTER VIEW staging.vw_teams
    OWNER TO admin;