-- CALL move_data_from_loading_to_staging();
CREATE OR REPLACE PROCEDURE prod.sp_migrate_players_data()
    LANGUAGE plpgsql
AS
$$
BEGIN
    -- Insert data from staging.players to prod.players
    INSERT INTO prod.fct_players (player_key,
                                 name,
                                 position,
                                 week,
                                 started,
                                 team_key,
                                 manager_name,
                                 league_id,
                                 league_season,
                                 points,
                                 passing_yards,
                                 passing_touchdowns,
                                 passing_interceptions,
                                 rushing_attempts,
                                 rushing_yards,
                                 rushing_touchdowns,
                                 receptions,
                                 receiving_yards,
                                 receiving_touchdowns,
                                 return_touchdowns,
                                 two_point_conversions,
                                 fumbles_lost,
                                 targets,
                                 offensive_fumble_return_td,
                                 field_goals_0_19_yards,
                                 field_goals_20_29_yards,
                                 field_goals_30_39_yards,
                                 field_goals_40_49_yards,
                                 field_goals_50_plus_yards,
                                 point_after_attempt_made,
                                 points_allowed,
                                 sack,
                                 interception,
                                 fumble_recovery,
                                 touchdown,
                                 safety,
                                 block_kick,
                                 kickoff_and_punt_return_touchdowns,
                                 points_allowed_0_points,
                                 points_allowed_1_6_points,
                                 points_allowed_7_13_points,
                                 points_allowed_14_20_points,
                                 points_allowed_21_27_points,
                                 points_allowed_28_34_points,
                                 points_allowed_35_plus_points,
                                 extra_point_returned,
                                 field_goals_made,
                                 field_goals_total_yards,
                                 field_goals_missed)
    SELECT player_key,
           name,
           position,
           week,
           started,
           team_key,
           manager_name,
           CAST(league_id AS INT),
           league_season,
           points,
           CAST("Passing Yards" AS INTEGER),
           CAST("Passing Touchdowns" AS INTEGER),
           CAST("Interceptions" AS INTEGER),
           CAST("Rushing Attempts" AS INTEGER),
           CAST("Rushing Yards" AS INTEGER),
           CAST("Rushing Touchdowns" AS INTEGER),
           CAST("Receptions" AS INTEGER),
           CAST(COALESCE("Reception Yards",
                         "Receiving Yards") AS INTEGER),
           CAST(COALESCE("Reception Touchdowns",
                         "Receiving Touchdowns") AS INTEGER),
           CAST("Return Touchdowns" AS INTEGER),
           CAST("2-Point Conversions" AS INTEGER),
           CAST("Fumbles Lost" AS INTEGER),
           CAST("Targets" AS INTEGER),
           CAST("Offensive Fumble Return TD" AS INTEGER),
           CAST("Field Goals 0-19 Yards" AS INTEGER),
           CAST("Field Goals 20-29 Yards" AS INTEGER),
           CAST("Field Goals 30-39 Yards" AS INTEGER),
           CAST("Field Goals 40-49 Yards" AS INTEGER),
           CAST("Field Goals 50+ Yards" AS INTEGER),
           CAST("Point After Attempt Made" AS INTEGER),
           CAST("Points Allowed" AS INTEGER),
           CAST("Sack" AS INTEGER),
           CAST("Interception" AS INTEGER),
           CAST("Fumble Recovery" AS INTEGER),
           CAST("Touchdown" AS INTEGER),
           CAST("Safety" AS INTEGER),
           CAST("Block Kick" AS INTEGER),
           CAST("Kickoff and Punt Return Touchdowns" AS INTEGER),
           CAST("Points Allowed 0 points" AS INTEGER),
           CAST("Points Allowed 1-6 points" AS INTEGER),
           CAST("Points Allowed 7-13 points" AS INTEGER),
           CAST("Points Allowed 14-20 points" AS INTEGER),
           CAST("Points Allowed 21-27 points" AS INTEGER),
           CAST("Points Allowed 28-34 points" AS INTEGER),
           CAST("Points Allowed 35+ points" AS INTEGER),
           CAST("Extra Point Returned" AS INTEGER),
           CAST("Field Goals Made" AS INTEGER),
           CAST("Field Goals Total Yards" AS INTEGER),
           CAST("Field Goals Missed" AS INTEGER)
    FROM staging.players
    ON CONFLICT ON CONSTRAINT players_natural_key -- Ensure uniqueness on the natural key
        DO UPDATE SET name                               = EXCLUDED.name,
                      position                           = EXCLUDED.position,
                      started                            = EXCLUDED.started,
                      team_key                           = EXCLUDED.team_key,
                      manager_name                       = EXCLUDED.manager_name,
                      points                             = EXCLUDED.points,
                      passing_yards                      = EXCLUDED.passing_yards,
                      passing_touchdowns                 = EXCLUDED.passing_touchdowns,
                      passing_interceptions              = EXCLUDED.passing_interceptions,
                      rushing_attempts                   = EXCLUDED.rushing_attempts,
                      rushing_yards                      = EXCLUDED.rushing_yards,
                      rushing_touchdowns                 = EXCLUDED.rushing_touchdowns,
                      receptions                         = EXCLUDED.receptions,
                      receiving_yards                    = EXCLUDED.receiving_yards,
                      receiving_touchdowns               = EXCLUDED.receiving_touchdowns,
                      return_touchdowns                  = EXCLUDED.return_touchdowns,
                      two_point_conversions              = EXCLUDED.two_point_conversions,
                      fumbles_lost                       = EXCLUDED.fumbles_lost,
                      targets                            = EXCLUDED.targets,
                      offensive_fumble_return_td         = EXCLUDED.offensive_fumble_return_td,
                      field_goals_0_19_yards             = EXCLUDED.field_goals_0_19_yards,
                      field_goals_20_29_yards            = EXCLUDED.field_goals_20_29_yards,
                      field_goals_30_39_yards            = EXCLUDED.field_goals_30_39_yards,
                      field_goals_40_49_yards            = EXCLUDED.field_goals_40_49_yards,
                      field_goals_50_plus_yards          = EXCLUDED.field_goals_50_plus_yards,
                      point_after_attempt_made           = EXCLUDED.point_after_attempt_made,
                      points_allowed                     = EXCLUDED.points_allowed,
                      sack                               = EXCLUDED.sack,
                      interception                       = EXCLUDED.interception,
                      fumble_recovery                    = EXCLUDED.fumble_recovery,
                      touchdown                          = EXCLUDED.touchdown,
                      safety                             = EXCLUDED.safety,
                      block_kick                         = EXCLUDED.block_kick,
                      kickoff_and_punt_return_touchdowns = EXCLUDED.kickoff_and_punt_return_touchdowns,
                      points_allowed_0_points            = EXCLUDED.points_allowed_0_points,
                      points_allowed_1_6_points          = EXCLUDED.points_allowed_1_6_points,
                      points_allowed_7_13_points         = EXCLUDED.points_allowed_7_13_points,
                      points_allowed_14_20_points        = EXCLUDED.points_allowed_14_20_points,
                      points_allowed_21_27_points        = EXCLUDED.points_allowed_21_27_points,
                      points_allowed_28_34_points        = EXCLUDED.points_allowed_28_34_points,
                      points_allowed_35_plus_points      = EXCLUDED.points_allowed_35_plus_points,
                      extra_point_returned               = EXCLUDED.extra_point_returned,
                      field_goals_made                   = EXCLUDED.field_goals_made,
                      field_goals_total_yards            = EXCLUDED.field_goals_total_yards,
                      field_goals_missed                 = EXCLUDED.field_goals_missed;

    -- Optional: You can add a DELETE or TRUNCATE statement here if you want to clear the `staging.matchups` table after migration
    -- DELETE FROM staging.players;

END;
$$;