INSERT INTO prod.dim_person (identity, person_name, is_active, full_name)
VALUES (28, 'G. WILLIAMS III', TRUE, 'Gil Williams III'),
       (64, 'M. MCFALL', FALSE, 'Marcus McFall'),
       (65, 'D. MARTIN', FALSE, 'Dalton Martin'),
       (10, 'T. WYCOFF', FALSE, 'Taylor Wycoff'),
       (13, 'I. MACK', FALSE, 'Isaiah Mack'),
       (14, 'A. SCHURR', FALSE, 'AJ Schurr'),
       (15, 'A. AZZATO', TRUE, 'Anthony Azzato'),
       (16, 'B. SCHMIDT', TRUE, 'Brady Schmidt'),
       (17, 'J. DUGUID', TRUE, 'Jake Duguid'),
       (18, 'M. THURMAN', TRUE, 'Mack Thurman'),
       (19, 'M. SCHMITZ', TRUE, 'Michael Schmitz'),
       (20, 'M. KLEIN', TRUE, 'Mikey Klein'),
       (21, 'R. DITTMAN', TRUE, 'Robbie Dittman'),
       (22, 'R. BARTH', FALSE, 'Ryan Barth'),
       (23, 'G. WILLIAMS IV', TRUE, 'Gibby Williams IV'),
       (24, 'M. JACOBSON', TRUE, 'Matt Jacobson'),
       (25, 'A. TAYLOR', FALSE, 'Alex Taylor'),
       (26, 'B. STOCK', TRUE, 'Bill Stock'),
       (27, 'D. ALLEN', TRUE, 'David Allen'),
       (29, 'J. TRAVERS', FALSE, 'Jerry Travers'),
       (30, 'J. SCHMITZ', TRUE, 'John Schmitz'),
       (66, 'J. LUEHRSEN', TRUE, 'John Luehrsen'),
       (67, 'M. EADES', FALSE, 'Mike Eades'),
       (31, 'B. KAY', TRUE, 'Bob Kay'),
       (32, 'S. FANCHER', TRUE, 'Scott Fancher'),
       (40, 'J. TEDDER', FALSE, 'Joe Tedder'),
       (44, 'AUGUST', FALSE, 'August'),
       (45, 'CARTER', FALSE, 'Carter'),
       (46, 'N. PERRY', FALSE, 'Nate'),
       (48, 'BRIAN', FALSE, 'Brian'),
       (49, 'CHANCE', FALSE, 'Chance'),
       (50, 'DAVID', FALSE, 'David'),
       (51, 'DAVID I', FALSE, 'David_I'),
       (52, 'JAKE', FALSE, 'Jake'),
       (53, 'K. BENNETT', FALSE, 'Keith Bennett'),
       (54, 'MATT', FALSE, 'Matt'),
       (55, 'NICK', FALSE, 'Nick'),
       (56, 'R. SHAFIQ', FALSE, 'Razi Shafiq'),
       (57, 'R. DOLGIN', FALSE, 'Ronny Dolgin'),
       (58, 'S. DOLGIN', FALSE, 'Sammy Dolgin'),
       (59, 'TAYLOR', FALSE, 'Taylor'),
       (60, 'TJ', FALSE, 'TJ'),
       (61, 'DUSTIN', FALSE, 'Dustin'),
       (62, 'NATHAN', FALSE, 'Nathan'),
       (1, 'D. ANGEL', TRUE, 'Diego Angel'),
       (2, 'A. KNIGHT', TRUE, 'Alex Knight'),
       (3, 'M. STAMMEN', TRUE, 'Marcus Stammen'),
       (4, 'M. RAMIREZ', TRUE, 'Manny Ramirez'),
       (5, 'P. MCGUSHIN', TRUE, 'Patrick McGushin'),
       (6, 'R. SCHWINN', TRUE, 'Richard Schwinn'),
       (7, 'R. OAKES', TRUE, 'Ryan Oakes'),
       (8, 'S. WARD', TRUE, 'Steve Ward'),
       (9, 'T. FANCHER', TRUE, 'Tony Fancher'),
       (11, 'A. ZACK', TRUE, 'Adam Zack'),
       (12, 'I. HASAN', TRUE, 'Imran Hasan'),
       (33, 'A. ZARA', TRUE, 'Alex Zara'),
       (34, 'A. SWETNAM', TRUE, 'Andrew Swetnam'),
       (35, 'T. PISANI', TRUE, 'Tony Pisani'),
       (36, 'B. TEETER', TRUE, 'Ben Teeter'),
       (37, 'B. ISLEY', TRUE, 'Brian Isley'),
       (38, 'O. SALAZAR', TRUE, 'Oscar Salazar'),
       (39, 'G. HARDAWAY', TRUE, 'Geoff Hardaway'),
       (41, 'S. TURETSKY', TRUE, 'Steve Turetsky'),
       (42, 'W. HIGHTOWER', TRUE, 'Will Hightower'),
       (43, 'Z. HILBORN', TRUE, 'Zach Hilborn'),
       (47, 'H. COHEN', TRUE, 'Hyman Cohen'),
       (63, 'A. HOLMES', TRUE, 'Alex Holmes');



CREATE TABLE prod.dim_league_categories
(
    identity    SERIAL PRIMARY KEY,
    league_name VARCHAR(255) NOT NULL CHECK (league_name <> '')
);