-- Matchups Table
CREATE TABLE staging.matchups
(
    id                      SERIAL PRIMARY KEY,
    week                    INTEGER,
    is_playoffs             BOOLEAN,
    is_consolation          BOOLEAN,
    team_1_key              TEXT,
    team_1_nickname         TEXT,
    team_1_points           FLOAT,
    team_1_projected_points FLOAT,
    is_bye                  BOOLEAN,
    team_2_key              TEXT,
    team_2_nickname         TEXT,
    team_2_points           FLOAT,
    team_2_projected_points FLOAT,
    league_id               INTEGER,
    league_season           INTEGER,
    league_key              TEXT
);

-- Teams Table
CREATE TABLE staging.teams
(
    id                SERIAL PRIMARY KEY,
    name              TEXT,
    team_key          TEXT,
    number_of_moves   INTEGER,
    number_of_trades  INTEGER,
    clinched_playoffs BOOLEAN,
    manager_name      TEXT,
    division_id       INTEGER,
    draft_grade       TEXT,
    rank              INTEGER,
    points_for        FLOAT,
    points_against    FLOAT,
    wins              INTEGER,
    losses            INTEGER,
    league_id         INTEGER,
    league_season     INTEGER,
    league_key        TEXT
);


-- Players Table
CREATE TABLE staging.players
(
    id                                   SERIAL PRIMARY KEY,
    player_key                           TEXT,
    name                                 TEXT,
    position                             TEXT,
    week                                 INTEGER,
    started                              BOOLEAN,
    team_key                             TEXT,
    manager_name                         TEXT,
    league_id                            FLOAT,
    league_season                        INT,
    league_key                           TEXT,
    points                               FLOAT,
    "Passing Yards"                      FLOAT,
    "Passing Touchdowns"                 FLOAT,
    "Interceptions"                      FLOAT,
    "Rushing Attempts"                   FLOAT,
    "Rushing Yards"                      FLOAT,
    "Rushing Touchdowns"                 FLOAT,
    "Receptions"                         FLOAT,
    "Receiving Yards"                    FLOAT,
    "Receiving Touchdowns"               FLOAT,
    "Reception Yards"                    FLOAT,
    "Reception Touchdowns"               FLOAT,
    "Return Touchdowns"                  FLOAT,
    "2-Point Conversions"                FLOAT,
    "Fumbles Lost"                       FLOAT,
    "Targets"                            FLOAT,
    "Offensive Fumble Return TD"         FLOAT,
    "Field Goals 0-19 Yards"             FLOAT,
    "Field Goals 20-29 Yards"            FLOAT,
    "Field Goals 30-39 Yards"            FLOAT,
    "Field Goals 40-49 Yards"            FLOAT,
    "Field Goals 50+ Yards"              FLOAT,
    "Point After Attempt Made"           FLOAT,
    "Points Allowed"                     FLOAT,
    "Sack"                               FLOAT,
    "Interception"                       FLOAT,
    "Fumble Recovery"                    FLOAT,
    "Touchdown"                          FLOAT,
    "Safety"                             FLOAT,
    "Block Kick"                         FLOAT,
    "Kickoff and Punt Return Touchdowns" FLOAT,
    "Points Allowed 0 points"            FLOAT,
    "Points Allowed 1-6 points"          FLOAT,
    "Points Allowed 7-13 points"         FLOAT,
    "Points Allowed 14-20 points"        FLOAT,
    "Points Allowed 21-27 points"        FLOAT,
    "Points Allowed 28-34 points"        FLOAT,
    "Points Allowed 35+ points"          FLOAT,
    "Extra Point Returned"               FLOAT,
    "Field Goals Made"                   FLOAT,
    "Field Goals Total Yards"            FLOAT,
    "Field Goals Missed"                 FLOAT
);