player_key,
name,
position,
week,
started,
team_key,
manager_name,
points,
Passing Yards,
Passing Touchdowns,
Interceptions,
Rushing Attempts,
Rushing Yards,
Rushing Touchdowns,
Targets,
Receptions,
Receiving Yards,
Receiving Touchdowns,
Return Touchdowns,
2-Point Conversions,
Fumbles Lost,
Offensive Fumble Return TD,
Field Goals 0-19 Yards,
Field Goals 20-29 Yards,
Field Goals 30-39 Yards,
Field Goals 40-49 Yards,
Field Goals 50+ Yards,
Point After Attempt Made,
Points Allowed,
Sack,
Interception,
Fumble Recovery,
Touchdown,
Safety,
Block Kick,
Kickoff and Punt Return Touchdowns,
Points Allowed 0 points,
Points Allowed 1-6 points,
Points Allowed 7-13 points,
Points Allowed 14-20 points,
Points Allowed 21-27 points,
Points Allowed 28-34 points,
Points Allowed 35+ points,
Extra Point Returned